### ISSUE TITLE
Xcode 11 added modal windows, breaks this plugin

### ISSUE THREAD

**Issue by TDola** [DmcSDK/cordova-plugin-mediaPicker#90]
![1042022823](https://user-images.githubusercontent.com/30079906/68413317-a1ff5500-0153-11ea-80cf-43b167e13ad6.jpg)
As shown, plugins are no longer full screen and have to be fixed one at a time.  If a user drags down and dismisses the window, no callbacks are ever called.

**Comment by Mr-Anonymous** [comment]
Good one. After seeing this, I tested it myself in my development app that is build using Xcode 11.2. I noticed 2 things:

1. The texts are in white and the background is in white as well which hides the album names such as: `Favourites, selfies, panorama etc, `

2. The issue pointed out above is there and the plugin modal is not in full screen.

![2019-11-07](https://user-images.githubusercontent.com/8770270/68449571-b1db6f80-020d-11ea-9094-162c5a7c11c4.jpg)

**Comment by TDola** [comment]
Hmm I am working on a way to catch when a modal window is closed by the user using the cordova resume events.  But if there are also issues like you should with the text.  I might have to fall back to the cordova gallery until this is fixed.  Hopefully these can be fixed quickly.

**Comment by Mr-Anonymous** [comment]
I wonder if @DmcSDK can take a look at this. He has been great with maintaining this plugin and I hope he can get some spare time now.

If incase he is unable to, I have to release my app in 3 days (by wed), what do you suggest I can do? I can't release the app when the modal selection alignment is like this.

**Comment by DmcSDK** [comment]
@TDola @Mr-Anonymous  ok i try fix this

**Comment by Mr-Anonymous** [comment]
Thank you so much @DmcSDK

**Comment by DmcSDK** [comment]
@Mr-Anonymous  i try fix ，u can test new version by github，but  i can't  reproduce text color bug,.

**Comment by DmcSDK** [comment]
@Mr-Anonymous note： The new version takePhoto API adjusts the parameter position

**Comment by Mr-Anonymous** [comment]
Hi @DmcSDK Thank you for the update.

I updated this plugin from 2.4.6 to 2.4.7 and did a test in simulator. It appears the modal alignment looks about the same as before.

I did the update like this:

```
cordova plugin rm cordova-plugin-mediapicker-dmcsdk 
cordova plugin add https://github.com/DmcSDK/cordova-plugin-mediaPicker.git --variable IOS_PHOTO_LIBRARY_USAGE_DESCRIPTION="This app needs photo library access to upload photos or videos from your device" --save
```

This is how it looks. Is it supposed to be like this? I forgot how it was previously:
![Screenshot 2019-11-11 at 11 36 02 PM](https://user-images.githubusercontent.com/8770270/68609802-5266b380-04dc-11ea-9eca-263e7aee3a45.png)

Plugin version:
```
cordova-plugin-mediapicker-dmcsdk 2.4.7 "MediaPicker"
```

**Comment by DmcSDK** [comment]
@Mr-Anonymous ok，i should modal full not work, text white bug been fixed？

**Comment by Mr-Anonymous** [comment]
@DmcSDK The white text seems to be fixed now. The text is showing correctly in black with white background. Only the modal is not full screen.

**Comment by ryaa** [comment]
I implemented the change to fix the problem with dialog dismissal (see my pull request for details). You can try to install it to see if this works
```
cordova plugin add https://github.com/ryaa/cordova-plugin-mediaPicker.git --variable IOS_PHOTO_LIBRARY_USAGE_DESCRIPTION="your message"
```

**Comment by TDola** [comment]
@ryaa Just to be certain I got the fix.  The window still shows as modal, but can't be dismissed by dragging down?  That's the behaviour I am seeing now with the latest version. Is this correct?

**Comment by ryaa** [comment]
> @ryaa Just to be certain I got the fix. The window still shows as modal, but can't be dismissed by dragging down? That's the behaviour I am seeing now with the latest version. Is this correct?

Yes. The fix is to disable dismissing the dialog when the user swipes down. The option could be to handle this swipe down gesture and act accordingly (for example, dismiss as if the user tap Cancel) however there could be the case when the user can start swiping down, stop and then swipe up back. Just not to complicate things I just disabled it.

Btw, the pull request with the change has been already accepted and merged into the repo master.

**Comment by TDola** [comment]
> > @ryaa Just to be certain I got the fix. The window still shows as modal, but can't be dismissed by dragging down? That's the behaviour I am seeing now with the latest version. Is this correct?
> 
> Yes. The fix is to disable dismissing the dialog when the user swipes down. The option could be to handle this swipe down gesture and act accordingly (for example, dismiss as if the user tap Cancel) however there could be the case when the user can start swiping down, stop and then swipe up back. Just not to complicate things I just disabled it.
> 
> Btw, the pull request with the change has been already accepted and merged into the repo master.

Thank you.  Closing this issue as complete

**Comment by Mr-Anonymous** [comment]
Thank you @ryaa @DmcSDK and @TDola 

I will update the plugin and submit my app to app store for review now. Thanks heaps for continuing to maintain this very useful plugin.

**Comment by Mr-Anonymous** [comment]
Is it possible that fix done in this is causing the `UIViewController` issue that I am having here: https://github.com/DmcSDK/cordova-plugin-mediaPicker/issues/104

I understand  iOS 13 brings some changes to how modals work. So I am wondering if anything related to this is causing the app to crash in some devices.
